# Generated by Django 5.2.6 on 2025-09-17 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название планеты')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('system', models.CharField(blank=True, max_length=100, verbose_name='Система/Сектор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('population', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Население')),
                ('climate', models.CharField(blank=True, max_length=50, verbose_name='Климат')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Публикация')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя персонажа')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('species', models.CharField(blank=True, max_length=50, verbose_name='Вид')),
                ('affiliation', models.CharField(blank=True, max_length=100, verbose_name='Фракция')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('is_published', models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0, verbose_name='Публикация')),
                ('homeworld', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='encyclopedia.planet', verbose_name='Родная планета')),
            ],
        ),
    ]
