# Generated by Django 5.2.6 on 2025-09-14 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название планеты')),
                ('system', models.CharField(blank=True, max_length=100, verbose_name='Система/Сектор')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('population', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Население')),
                ('climate', models.CharField(blank=True, max_length=50, verbose_name='Климат')),
            ],
        ),
        migrations.AlterModelOptions(
            name='character',
            options={},
        ),
        migrations.RemoveField(
            model_name='character',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='character',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='character',
            name='affiliation',
            field=models.CharField(blank=True, max_length=100, verbose_name='Аффилиация/Фракция'),
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.CharField(blank=True, max_length=50, verbose_name='Вид'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Имя персонажа'),
        ),
        migrations.AddField(
            model_name='character',
            name='homeworld',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='encyclopedia.planet', verbose_name='Родная планета'),
        ),
    ]
