# Generated by Django 5.2.6 on 2025-09-17 18:21

from django.db import migrations
from django.utils.text import slugify


def generate_slugs(apps, schema_editor):
    Character = apps.get_model('encyclopedia', 'Character')
    Planet = apps.get_model('encyclopedia', 'Planet')
    
    # Генерируем слаги для персонажей
    for character in Character.objects.filter(slug__isnull=True):
        character.slug = slugify(character.name)
        character.save()
    
    # Генерируем слаги для планет
    for planet in Planet.objects.filter(slug__isnull=True):
        planet.slug = slugify(planet.name)
        planet.save()


def reverse_generate_slugs(apps, schema_editor):
    # Обратная функция - очищаем слаги
    Character = apps.get_model('encyclopedia', 'Character')
    Planet = apps.get_model('encyclopedia', 'Planet')
    
    Character.objects.update(slug=None)
    Planet.objects.update(slug=None)


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0002_alter_character_slug_alter_planet_slug'),
    ]

    operations = [
        migrations.RunPython(generate_slugs, reverse_generate_slugs),
    ]
