# Generated by Django 5.2.6 on 2025-09-17 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encyclopedia', '0003_auto_20250918_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название фракции')),
                ('side', models.CharField(blank=True, max_length=50, verbose_name='Сторона силы')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Фракция',
                'verbose_name_plural': 'Фракции',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Тег')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='CharacterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lightsaber_color', models.CharField(blank=True, max_length=30, verbose_name='Цвет светового меча')),
                ('birth_year', models.CharField(blank=True, max_length=20, verbose_name='Год рождения')),
                ('midichlorians', models.PositiveIntegerField(blank=True, null=True, verbose_name='Мидихлорианы')),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='encyclopedia.character', verbose_name='Персонаж')),
            ],
            options={
                'verbose_name': 'Детали персонажа',
                'verbose_name_plural': 'Детали персонажей',
            },
        ),
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='encyclopedia.faction', verbose_name='Фракция (модель)'),
        ),
        migrations.AddField(
            model_name='character',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='characters', to='encyclopedia.tag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='planet',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='planets', to='encyclopedia.tag', verbose_name='Теги'),
        ),
    ]
